from django.urls import path
from . import views

urlpatterns = [
    path("MasterData", views.MasterDataListView.as_view()),
    path("MasterData/car-brands/<int:brand_id>/models", views.BrandModelsView.as_view()),
    path("MasterData/<str:kind>", views.MasterDataListView.as_view()),
    path("masterdata", views.MasterDataListView.as_view()),
    path("masterdata/car-brands/<int:brand_id>/models", views.BrandModelsView.as_view()),
    path("masterdata/<str:kind>", views.MasterDataListView.as_view()),
    path("Cars", views.CarListCreateView.as_view()),
    path("Cars/filter", views.CarListCreateView.as_view()),
    path("Cars/mine", views.MyCarsView.as_view()),
    path("Cars/favorites", views.FavoritesView.as_view()),
    path("Cars/upload", views.CarUploadView.as_view()),
    path("Cars/seller/<int:seller_id>", views.SellerCarsPublicView.as_view()),
    path("Cars/<int:car_id>/related", views.RelatedCarsView.as_view()),
    path("Cars/<int:car_id>/favorite", views.FavoriteActionView.as_view()),
    path("Cars/<int:car_id>", views.CarDetailView.as_view()),
    path("cars", views.CarListCreateView.as_view()),
    path("cars/filter", views.CarListCreateView.as_view()),
    path("cars/mine", views.MyCarsView.as_view()),
    path("cars/favorites", views.FavoritesView.as_view()),
    path("cars/upload", views.CarUploadView.as_view()),
    path("cars/seller/<int:seller_id>", views.SellerCarsPublicView.as_view()),
    path("cars/<int:car_id>/related", views.RelatedCarsView.as_view()),
    path("cars/<int:car_id>/favorite", views.FavoriteActionView.as_view()),
    path("cars/<int:car_id>", views.CarDetailView.as_view()),
    path("cars/<int:car_id>/history", views.VehicleHistoryListView.as_view()),
    path("vehicle-history/<int:history_id>", views.VehicleHistoryDetailView.as_view()),
    path("seller/cars", views.MyCarsView.as_view()),
    path("seller/cars/<int:car_id>", views.SellerCarDetailView.as_view()),
    path("seller/cars/<int:car_id>/images", views.SellerCarImagesView.as_view()),
    path("seller/cars/<int:car_id>/images/<int:image_id>/retry", views.SellerCarImageRetryView.as_view()),
    path("seller/statistics", views.SellerDashboardView.as_view()),
    path("seller/cars/<int:car_id>/status", views.SellerCarStatusView.as_view()),
    path("seller/listing-draft", views.ListingDraftView.as_view()),
    path("saved-searches", views.SavedSearchListView.as_view()),
    path("saved-searches/<int:search_id>", views.SavedSearchDetailView.as_view()),
]
