# Generated by Django 6.0.7 on 2026-07-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_make_outbox_public_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclehistory',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle-history/'),
        ),
    ]
