# Generated by Django 6.0.7 on 2026-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_vehiclehistory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrealtimepresence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
