# Generated by Django 6.0.7 on 2026-07-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_userrealtimepresence_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['seller', 'status', '-listed_date'], name='car_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['seller', 'is_read', '-created_at'], name='contact_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-sent_at', '-id'], name='message_chat_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_read', 'sender'], name='message_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationhistory',
            index=models.Index(fields=['car', '-created_at'], name='moderation_history_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notification_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeoutboxevent',
            index=models.Index(fields=['processed_at', 'dead_lettered_at', 'created_at'], name='outbox_dispatch_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='report_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['seller', 'status', '-created_at'], name='review_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['is_enabled', 'brand', 'model'], name='saved_search_match_idx'),
        ),
    ]
