# Generated by Django 5.2.16 on 2026-07-23 07:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


def normalise_main_images(apps, schema_editor):
    CarImage = apps.get_model("marketplace", "CarImage")
    seen = set()
    for image in CarImage.objects.filter(is_main=True).order_by("car_id", "display_order", "id"):
        if image.car_id in seen:
            CarImage.objects.filter(id=image.id).update(is_main=False)
        else:
            seen.add(image.car_id)


def seed_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("marketplace", "FeatureFlag")
    FeatureFlag.objects.get_or_create(
        key="cursor-pagination",
        defaults={"description": "Signed cursor pagination for messages and notifications.", "is_enabled": True},
    )
    FeatureFlag.objects.get_or_create(
        key="postgres-full-text-search",
        defaults={"description": "PostgreSQL full-text and trigram listing search.", "is_enabled": True},
    )


def create_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    Car = apps.get_model("marketplace", "Car")
    schema_editor.add_index(
        Car,
        django.contrib.postgres.indexes.GinIndex(
            django.contrib.postgres.search.SearchVector("title", "description", "city", config="simple"),
            name="car_search_vector_idx",
        ),
    )
    schema_editor.add_index(
        Car,
        django.contrib.postgres.indexes.GinIndex(
            fields=["title"], name="car_title_trgm_idx", opclasses=["gin_trgm_ops"]
        ),
    )


def drop_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    Car = apps.get_model("marketplace", "Car")
    schema_editor.remove_index(
        Car,
        django.contrib.postgres.indexes.GinIndex(
            django.contrib.postgres.search.SearchVector("title", "description", "city", config="simple"),
            name="car_search_vector_idx",
        ),
    )
    schema_editor.remove_index(
        Car,
        django.contrib.postgres.indexes.GinIndex(
            fields=["title"], name="car_title_trgm_idx", opclasses=["gin_trgm_ops"]
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_car_car_seller_status_idx_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(default='Unknown device', max_length=160)),
                ('browser', models.CharField(default='Unknown browser', max_length=160)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(seed_feature_flags, migrations.RunPython.noop),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100)),
                ('actor_key', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_search_indexes, drop_search_indexes)],
            state_operations=[
                migrations.AddIndex(
                    model_name='car',
                    index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'description', 'city', config='simple'), name='car_search_vector_idx'),
                ),
                migrations.AddIndex(
                    model_name='car',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='car_title_trgm_idx', opclasses=['gin_trgm_ops']),
                ),
            ],
        ),
        migrations.RunPython(normalise_main_images, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('car',), name='unique_main_image_per_car'),
        ),
        migrations.AddField(
            model_name='authsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['scope', 'actor_key', 'key'], name='idempotency_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('scope', 'actor_key', 'key'), name='unique_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'revoked_at', '-last_activity_at'], name='auth_session_active_idx'),
        ),
    ]
